name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Specify the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install  # Adjust this command based on your project setup

      - name: Build site
        run: npm run build  # Adjust this command based on your project setup

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Specify the branch where GitHub Pages are hosted
          FOLDER: build  # Specify the folder where your built site resides
